import { Request, Response, Router } from 'express';
import { NanoSessionFacilitatorHandler } from '@nanosession/server';
import { NanoRpcClient } from '@nanosession/rpc';
import { registerSession } from './status';

// Lazy-initialize to ensure dotenv has loaded env vars before we read them
let _rpcClient: NanoRpcClient | null = null;
let _facilitator: NanoSessionFacilitatorHandler | null = null;

function getRpcClient(): NanoRpcClient {
    if (!_rpcClient) {
        if (!process.env.NANO_RPC_URL) {
            throw new Error('NANO_RPC_URL environment variable is not set');
        }
        _rpcClient = new NanoRpcClient({
            endpoints: [process.env.NANO_RPC_URL],
            timeoutMs: 15000
        });
    }
    return _rpcClient;
}

function getFacilitator(): NanoSessionFacilitatorHandler {
    if (!_facilitator) {
        _facilitator = new NanoSessionFacilitatorHandler({
            rpcClient: getRpcClient(),
            // Uses default InMemorySpentSet with TTL
            // Uses default in-memory session registry
        });
    }
    return _facilitator;
}

/**
 * Determine the base URL for the resource based on request headers.
 * Precedence: X-Forwarded-Host > X-Proxy-Host > Host
 * Protocol: X-Forwarded-Proto > req.protocol
 */
function getResourceBaseUrl(req: Request): string {
    // Protocol: check X-Forwarded-Proto first (standard proxy header)
    const proto = req.header('X-Forwarded-Proto') || req.protocol;

    // Host: precedence for proxy scenarios
    const forwardedHost = req.header('X-Forwarded-Host');
    const proxyHost = req.header('X-Proxy-Host');
    const hostHeader = req.header('Host');

    // Use first available host in precedence order
    const host = forwardedHost || proxyHost || hostHeader || 'localhost:3001';

    return `${proto}://${host}`;
}

export const protectedRoute = Router();

protectedRoute.get('/', async (req: Request, res: Response) => {
    const paymentProof = req.header('X-Payment-Block');
    const incomingSessionId = req.header('X-Payment-Session');
    const facilitator = getFacilitator();

    // If the client provided a block hash, verify it
    if (paymentProof && incomingSessionId) {
        // Retrieve the stored requirements for this session
        const storedReqs = facilitator.getStoredRequirements(incomingSessionId);

        if (!storedReqs) {
            res.status(402).json({ error: "Session not found or expired. Please request a new payment." });
            return;
        }

        try {
            // Settle the payment (verifies AND marks as spent)
            const result = await facilitator.handleSettle(storedReqs, { blockHash: paymentProof });

            if (result?.success) {
                const exclusiveContent = `
                    <div class="exclusive-content">
                        <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/TAT35tflCUM?si=TAzGQJ9jmgDuFgnw&amp;controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                        <p><em>This content was protected by a real Nano payment. No accounts, no sign-ups, no tracking. Just pay and access. If you were an agent, this and other x402 payments could be made frictionless by using <a href="https://github.com/CasualSecurityInc/x402.NanoSession/tree/main/packages" target="_blank" rel="noopener noreferrer">our client packages</a>.</em></p>
                    </div>
                `;
                res.json({
                    success: true,
                    message: "Payment accepted! You have access to the protected demo content.",
                    html: exclusiveContent
                });
                return;
            } else {
                res.status(402).json({ error: result?.error || "Invalid payment proof" });
                return;
            }
        } catch (e) {
            console.error('Settlement error:', e);
            res.status(500).json({ error: "Verification error on server" });
            return;
        }
    }

    // No proof provided, demand payment
    const amountToCharge = '10000000000000000000000000000'; // 0.01 XNO in Raw
    const payToAddress = process.env.NANO_SERVER_ADDRESS!;

    // Generate x402 requirements (automatically registers session in-memory)
    const reqs = facilitator.getRequirements({
        amount: amountToCharge,
        payTo: payToAddress,
        maxTimeoutSeconds: 600 // 10 minute timeout
    });

    if (process.env.NANO_RPC_URL?.includes('beta') || process.env.NANO_RPC_URL?.includes('testnet') || process.env.NANO_WS_URL?.includes('peering')) {
        reqs.network = 'nano:testnet';
    }

    // Use the sessionId generated by the facilitator
    const newSessionId = reqs.extra.sessionId;

    // The FacilitatorHandler has likely already added a random tag
    const taggedAmountRaw = (BigInt(reqs.amount) + BigInt(reqs.extra.tag)).toString();

    // Register the session in our SSE tracker so we can push real-time updates
    registerSession(newSessionId, taggedAmountRaw);

    // Return the HTTP 402 with PaymentRequired schema
    res.status(402)
        .setHeader('X-Payment-Required', JSON.stringify(reqs))
        .json({
            x402Version: 5,
            error: 'Payment Required',
            resource: {
                url: `${getResourceBaseUrl(req)}/api/protected`,
                description: 'Access to protected demo content',
                mimeType: 'application/json'
            },
            accepts: [reqs]
        });
});
